export default {
  APP_CHANGE_LOCALE: 'APP_CHANGE_LOCALE',
  EXAMPLE: 'EXAMPLE',
  REQUEST_ASYNC_DATA: 'REQUEST_ASYNC_DATA',
  RECEIVE_ASYNC_DATA: 'RECEIVE_ASYNC_DATA',
  FAILED_RECEIVE_ASYNC_DATA: 'FAILED_RECEIVE_ASYNC_DATA',
};
